//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// Defines values for RerankerM0RequestModel.
const (
	JinaRerankerM0 RerankerM0RequestModel = "jina-reranker-m0"
)

// Valid indicates whether the value is a known member of the RerankerM0RequestModel enum.
func (e RerankerM0RequestModel) Valid() bool {
	switch e {
	case JinaRerankerM0:
		return true
	default:
		return false
	}
}

// Defines values for RerankerV3RequestModel.
const (
	JinaRerankerV3  RerankerV3RequestModel = "jina-reranker-v3"
	JinaRerankerV35 RerankerV3RequestModel = "jina-reranker-v3.5"
)

// Valid indicates whether the value is a known member of the RerankerV3RequestModel enum.
func (e RerankerV3RequestModel) Valid() bool {
	switch e {
	case JinaRerankerV3:
		return true
	case JinaRerankerV35:
		return true
	default:
		return false
	}
}

// Defines values for TextRerankerRequestModel.
const (
	JinaColbertV1En                TextRerankerRequestModel = "jina-colbert-v1-en"
	JinaColbertV2                  TextRerankerRequestModel = "jina-colbert-v2"
	JinaRerankerV1BaseEn           TextRerankerRequestModel = "jina-reranker-v1-base-en"
	JinaRerankerV1TinyEn           TextRerankerRequestModel = "jina-reranker-v1-tiny-en"
	JinaRerankerV1TurboEn          TextRerankerRequestModel = "jina-reranker-v1-turbo-en"
	JinaRerankerV2BaseMultilingual TextRerankerRequestModel = "jina-reranker-v2-base-multilingual"
)

// Valid indicates whether the value is a known member of the TextRerankerRequestModel enum.
func (e TextRerankerRequestModel) Valid() bool {
	switch e {
	case JinaColbertV1En:
		return true
	case JinaColbertV2:
		return true
	case JinaRerankerV1BaseEn:
		return true
	case JinaRerankerV1TinyEn:
		return true
	case JinaRerankerV1TurboEn:
		return true
	case JinaRerankerV2BaseMultilingual:
		return true
	default:
		return false
	}
}

// BaseUsage defines model for BaseUsage.
type BaseUsage struct {
	// TotalTokens Total number of tokens processed.
	TotalTokens int `json:"total_tokens"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code for programmatic handling
	Code *string `json:"code,omitempty"`

	// Detail Human-readable error message
	Detail string `json:"detail"`

	// RequestId Unique request identifier for tracing and support
	RequestId *string `json:"request_id,omitempty"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   *string     `json:"field,omitempty"`
		Input   interface{} `json:"input,omitempty"`
		Message *string     `json:"message,omitempty"`
		Type    *string     `json:"type,omitempty"`
	} `json:"errors,omitempty"`
}

// ImageDoc defines model for ImageDoc.
type ImageDoc struct {
	// Image Image as a URL or base64-encoded string.
	Image string `json:"image"`
}

// RerankerM0Request Multimodal reranking for text and images.
type RerankerM0Request struct {
	// Documents Documents to rank: strings, `TextDoc`, or `ImageDoc` objects.
	Documents []RerankerM0Request_Documents_Item `json:"documents"`

	// Model The multimodal reranking model to use.
	Model RerankerM0RequestModel `json:"model"`

	// Query The query to rank documents against: a text string, or an image object (`{"image": <url|base64>}`) for a visual query.
	Query RerankerM0Request_Query `json:"query"`

	// ReturnDocuments If true (default), includes document content in each result.
	ReturnDocuments *bool `json:"return_documents,omitempty"`

	// TopN Number of top results to return. If not set, returns all documents.
	TopN *int `json:"top_n,omitempty"`
}

// RerankerM0RequestDocuments0 defines model for RerankerM0Request.Documents.0.
type RerankerM0RequestDocuments0 = string

// RerankerM0Request_Documents_Item defines model for RerankerM0Request.documents.Item.
type RerankerM0Request_Documents_Item struct {
	union json.RawMessage
}

// RerankerM0RequestModel The multimodal reranking model to use.
type RerankerM0RequestModel string

// RerankerM0RequestQuery0 defines model for RerankerM0Request.Query.0.
type RerankerM0RequestQuery0 = string

// RerankerM0Request_Query The query to rank documents against: a text string, or an image object (`{"image": <url|base64>}`) for a visual query.
type RerankerM0Request_Query struct {
	union json.RawMessage
}

// RerankerV3Request Listwise reranker for high-quality multilingual retrieval. `max_doc_length`
// is an optional override; when omitted it stays `None` and the serving executor
// applies its configured per-model default, keeping that default in one place.
type RerankerV3Request struct {
	// Documents Documents to rank: strings or `TextDoc` objects.
	Documents []RerankerV3Request_Documents_Item `json:"documents"`

	// MaxDocLength Maximum tokens per document (1-8192). Omit to use the model's default (2048 for jina-reranker-v3, 8192 for jina-reranker-v3.5).
	MaxDocLength *int `json:"max_doc_length,omitempty"`

	// Model The reranking model to use.
	Model RerankerV3RequestModel `json:"model"`

	// Query The search query to rank documents against.
	Query string `json:"query"`

	// ReturnDocuments If true (default), includes document content in each result.
	ReturnDocuments *bool `json:"return_documents,omitempty"`

	// ReturnEmbeddings If true, returns the document embedding alongside the relevance score.
	ReturnEmbeddings *bool `json:"return_embeddings,omitempty"`

	// TopN Number of top results to return. If not set, returns all documents.
	TopN *int `json:"top_n,omitempty"`
}

// RerankerV3RequestDocuments0 defines model for RerankerV3Request.Documents.0.
type RerankerV3RequestDocuments0 = string

// RerankerV3Request_Documents_Item defines model for RerankerV3Request.documents.Item.
type RerankerV3Request_Documents_Item struct {
	union json.RawMessage
}

// RerankerV3RequestModel The reranking model to use.
type RerankerV3RequestModel string

// RerankingResponse Response containing ranked documents.
type RerankingResponse struct {
	// Model The model used for reranking.
	Model string `json:"model"`

	// Object Object type, always `list`.
	Object *string `json:"object,omitempty"`

	// Results Ranked documents, sorted by relevance score descending.
	Results []RerankingResult `json:"results"`

	// Usage Token usage statistics.
	Usage BaseUsage `json:"usage"`
}

// RerankingResult A single reranking result.
type RerankingResult struct {
	// Document Document content, if `return_documents=true`.
	Document *RerankingResult_Document `json:"document,omitempty"`

	// Embedding Document embedding, if `return_embeddings=true`.
	Embedding *[]float32 `json:"embedding,omitempty"`

	// Index Position of this document in the original input list.
	Index int `json:"index"`

	// RelevanceScore Relevance score. Higher is more relevant.
	RelevanceScore float32 `json:"relevance_score"`
}

// RerankingResultDocument0 defines model for RerankingResult.Document.0.
type RerankingResultDocument0 = string

// RerankingResult_Document Document content, if `return_documents=true`.
type RerankingResult_Document struct {
	union json.RawMessage
}

// TextDoc defines model for TextDoc.
type TextDoc struct {
	// Text Text content to process.
	Text string `json:"text"`
}

// TextRerankerRequest Text reranking request for v1/v2 models.
type TextRerankerRequest struct {
	// Documents Documents to rank: strings or `TextDoc` objects.
	Documents []TextRerankerRequest_Documents_Item `json:"documents"`

	// Model The reranking model to use.
	Model TextRerankerRequestModel `json:"model"`

	// Query The search query to rank documents against.
	Query string `json:"query"`

	// ReturnDocuments If true (default), includes document content in each result.
	ReturnDocuments *bool `json:"return_documents,omitempty"`

	// TopN Number of top results to return. If not set, returns all documents.
	TopN *int `json:"top_n,omitempty"`
}

// TextRerankerRequestDocuments0 defines model for TextRerankerRequest.Documents.0.
type TextRerankerRequestDocuments0 = string

// TextRerankerRequest_Documents_Item defines model for TextRerankerRequest.documents.Item.
type TextRerankerRequest_Documents_Item struct {
	union json.RawMessage
}

// TextRerankerRequestModel The reranking model to use.
type TextRerankerRequestModel string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// GatewayTimeout defines model for GatewayTimeout.
type GatewayTimeout = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// RerankV1RerankPostJSONBody defines parameters for RerankV1RerankPost.
type RerankV1RerankPostJSONBody struct {
	union json.RawMessage
}

// RerankV1RerankPostJSONRequestBody defines body for RerankV1RerankPost for application/json ContentType.
type RerankV1RerankPostJSONRequestBody RerankV1RerankPostJSONBody

// AsRerankerM0RequestDocuments0 returns the union data inside the RerankerM0Request_Documents_Item as a RerankerM0RequestDocuments0
func (t RerankerM0Request_Documents_Item) AsRerankerM0RequestDocuments0() (RerankerM0RequestDocuments0, error) {
	var body RerankerM0RequestDocuments0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRerankerM0RequestDocuments0 overwrites any union data inside the RerankerM0Request_Documents_Item as the provided RerankerM0RequestDocuments0
func (t *RerankerM0Request_Documents_Item) FromRerankerM0RequestDocuments0(v RerankerM0RequestDocuments0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRerankerM0RequestDocuments0 performs a merge with any union data inside the RerankerM0Request_Documents_Item, using the provided RerankerM0RequestDocuments0
func (t *RerankerM0Request_Documents_Item) MergeRerankerM0RequestDocuments0(v RerankerM0RequestDocuments0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextDoc returns the union data inside the RerankerM0Request_Documents_Item as a TextDoc
func (t RerankerM0Request_Documents_Item) AsTextDoc() (TextDoc, error) {
	var body TextDoc
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextDoc overwrites any union data inside the RerankerM0Request_Documents_Item as the provided TextDoc
func (t *RerankerM0Request_Documents_Item) FromTextDoc(v TextDoc) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextDoc performs a merge with any union data inside the RerankerM0Request_Documents_Item, using the provided TextDoc
func (t *RerankerM0Request_Documents_Item) MergeTextDoc(v TextDoc) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageDoc returns the union data inside the RerankerM0Request_Documents_Item as a ImageDoc
func (t RerankerM0Request_Documents_Item) AsImageDoc() (ImageDoc, error) {
	var body ImageDoc
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageDoc overwrites any union data inside the RerankerM0Request_Documents_Item as the provided ImageDoc
func (t *RerankerM0Request_Documents_Item) FromImageDoc(v ImageDoc) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageDoc performs a merge with any union data inside the RerankerM0Request_Documents_Item, using the provided ImageDoc
func (t *RerankerM0Request_Documents_Item) MergeImageDoc(v ImageDoc) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RerankerM0Request_Documents_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RerankerM0Request_Documents_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRerankerM0RequestQuery0 returns the union data inside the RerankerM0Request_Query as a RerankerM0RequestQuery0
func (t RerankerM0Request_Query) AsRerankerM0RequestQuery0() (RerankerM0RequestQuery0, error) {
	var body RerankerM0RequestQuery0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRerankerM0RequestQuery0 overwrites any union data inside the RerankerM0Request_Query as the provided RerankerM0RequestQuery0
func (t *RerankerM0Request_Query) FromRerankerM0RequestQuery0(v RerankerM0RequestQuery0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRerankerM0RequestQuery0 performs a merge with any union data inside the RerankerM0Request_Query, using the provided RerankerM0RequestQuery0
func (t *RerankerM0Request_Query) MergeRerankerM0RequestQuery0(v RerankerM0RequestQuery0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageDoc returns the union data inside the RerankerM0Request_Query as a ImageDoc
func (t RerankerM0Request_Query) AsImageDoc() (ImageDoc, error) {
	var body ImageDoc
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageDoc overwrites any union data inside the RerankerM0Request_Query as the provided ImageDoc
func (t *RerankerM0Request_Query) FromImageDoc(v ImageDoc) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageDoc performs a merge with any union data inside the RerankerM0Request_Query, using the provided ImageDoc
func (t *RerankerM0Request_Query) MergeImageDoc(v ImageDoc) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RerankerM0Request_Query) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RerankerM0Request_Query) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRerankerV3RequestDocuments0 returns the union data inside the RerankerV3Request_Documents_Item as a RerankerV3RequestDocuments0
func (t RerankerV3Request_Documents_Item) AsRerankerV3RequestDocuments0() (RerankerV3RequestDocuments0, error) {
	var body RerankerV3RequestDocuments0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRerankerV3RequestDocuments0 overwrites any union data inside the RerankerV3Request_Documents_Item as the provided RerankerV3RequestDocuments0
func (t *RerankerV3Request_Documents_Item) FromRerankerV3RequestDocuments0(v RerankerV3RequestDocuments0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRerankerV3RequestDocuments0 performs a merge with any union data inside the RerankerV3Request_Documents_Item, using the provided RerankerV3RequestDocuments0
func (t *RerankerV3Request_Documents_Item) MergeRerankerV3RequestDocuments0(v RerankerV3RequestDocuments0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextDoc returns the union data inside the RerankerV3Request_Documents_Item as a TextDoc
func (t RerankerV3Request_Documents_Item) AsTextDoc() (TextDoc, error) {
	var body TextDoc
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextDoc overwrites any union data inside the RerankerV3Request_Documents_Item as the provided TextDoc
func (t *RerankerV3Request_Documents_Item) FromTextDoc(v TextDoc) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextDoc performs a merge with any union data inside the RerankerV3Request_Documents_Item, using the provided TextDoc
func (t *RerankerV3Request_Documents_Item) MergeTextDoc(v TextDoc) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RerankerV3Request_Documents_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RerankerV3Request_Documents_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRerankingResultDocument0 returns the union data inside the RerankingResult_Document as a RerankingResultDocument0
func (t RerankingResult_Document) AsRerankingResultDocument0() (RerankingResultDocument0, error) {
	var body RerankingResultDocument0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRerankingResultDocument0 overwrites any union data inside the RerankingResult_Document as the provided RerankingResultDocument0
func (t *RerankingResult_Document) FromRerankingResultDocument0(v RerankingResultDocument0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRerankingResultDocument0 performs a merge with any union data inside the RerankingResult_Document, using the provided RerankingResultDocument0
func (t *RerankingResult_Document) MergeRerankingResultDocument0(v RerankingResultDocument0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextDoc returns the union data inside the RerankingResult_Document as a TextDoc
func (t RerankingResult_Document) AsTextDoc() (TextDoc, error) {
	var body TextDoc
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextDoc overwrites any union data inside the RerankingResult_Document as the provided TextDoc
func (t *RerankingResult_Document) FromTextDoc(v TextDoc) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextDoc performs a merge with any union data inside the RerankingResult_Document, using the provided TextDoc
func (t *RerankingResult_Document) MergeTextDoc(v TextDoc) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageDoc returns the union data inside the RerankingResult_Document as a ImageDoc
func (t RerankingResult_Document) AsImageDoc() (ImageDoc, error) {
	var body ImageDoc
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageDoc overwrites any union data inside the RerankingResult_Document as the provided ImageDoc
func (t *RerankingResult_Document) FromImageDoc(v ImageDoc) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageDoc performs a merge with any union data inside the RerankingResult_Document, using the provided ImageDoc
func (t *RerankingResult_Document) MergeImageDoc(v ImageDoc) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RerankingResult_Document) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RerankingResult_Document) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTextRerankerRequestDocuments0 returns the union data inside the TextRerankerRequest_Documents_Item as a TextRerankerRequestDocuments0
func (t TextRerankerRequest_Documents_Item) AsTextRerankerRequestDocuments0() (TextRerankerRequestDocuments0, error) {
	var body TextRerankerRequestDocuments0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextRerankerRequestDocuments0 overwrites any union data inside the TextRerankerRequest_Documents_Item as the provided TextRerankerRequestDocuments0
func (t *TextRerankerRequest_Documents_Item) FromTextRerankerRequestDocuments0(v TextRerankerRequestDocuments0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextRerankerRequestDocuments0 performs a merge with any union data inside the TextRerankerRequest_Documents_Item, using the provided TextRerankerRequestDocuments0
func (t *TextRerankerRequest_Documents_Item) MergeTextRerankerRequestDocuments0(v TextRerankerRequestDocuments0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextDoc returns the union data inside the TextRerankerRequest_Documents_Item as a TextDoc
func (t TextRerankerRequest_Documents_Item) AsTextDoc() (TextDoc, error) {
	var body TextDoc
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextDoc overwrites any union data inside the TextRerankerRequest_Documents_Item as the provided TextDoc
func (t *TextRerankerRequest_Documents_Item) FromTextDoc(v TextDoc) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextDoc performs a merge with any union data inside the TextRerankerRequest_Documents_Item, using the provided TextDoc
func (t *TextRerankerRequest_Documents_Item) MergeTextDoc(v TextDoc) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TextRerankerRequest_Documents_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TextRerankerRequest_Documents_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTextRerankerRequest returns the union data inside the RerankV1RerankPostJSONBody as a TextRerankerRequest
func (t RerankV1RerankPostJSONBody) AsTextRerankerRequest() (TextRerankerRequest, error) {
	var body TextRerankerRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextRerankerRequest overwrites any union data inside the RerankV1RerankPostJSONBody as the provided TextRerankerRequest
func (t *RerankV1RerankPostJSONBody) FromTextRerankerRequest(v TextRerankerRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextRerankerRequest performs a merge with any union data inside the RerankV1RerankPostJSONBody, using the provided TextRerankerRequest
func (t *RerankV1RerankPostJSONBody) MergeTextRerankerRequest(v TextRerankerRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRerankerM0Request returns the union data inside the RerankV1RerankPostJSONBody as a RerankerM0Request
func (t RerankV1RerankPostJSONBody) AsRerankerM0Request() (RerankerM0Request, error) {
	var body RerankerM0Request
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRerankerM0Request overwrites any union data inside the RerankV1RerankPostJSONBody as the provided RerankerM0Request
func (t *RerankV1RerankPostJSONBody) FromRerankerM0Request(v RerankerM0Request) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRerankerM0Request performs a merge with any union data inside the RerankV1RerankPostJSONBody, using the provided RerankerM0Request
func (t *RerankV1RerankPostJSONBody) MergeRerankerM0Request(v RerankerM0Request) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRerankerV3Request returns the union data inside the RerankV1RerankPostJSONBody as a RerankerV3Request
func (t RerankV1RerankPostJSONBody) AsRerankerV3Request() (RerankerV3Request, error) {
	var body RerankerV3Request
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRerankerV3Request overwrites any union data inside the RerankV1RerankPostJSONBody as the provided RerankerV3Request
func (t *RerankV1RerankPostJSONBody) FromRerankerV3Request(v RerankerV3Request) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRerankerV3Request performs a merge with any union data inside the RerankV1RerankPostJSONBody, using the provided RerankerV3Request
func (t *RerankV1RerankPostJSONBody) MergeRerankerV3Request(v RerankerV3Request) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RerankV1RerankPostJSONBody) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"model"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t RerankV1RerankPostJSONBody) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "jina-colbert-v1-en":
		return t.AsTextRerankerRequest()
	case "jina-colbert-v2":
		return t.AsTextRerankerRequest()
	case "jina-reranker-m0":
		return t.AsRerankerM0Request()
	case "jina-reranker-v1-base-en":
		return t.AsTextRerankerRequest()
	case "jina-reranker-v1-tiny-en":
		return t.AsTextRerankerRequest()
	case "jina-reranker-v1-turbo-en":
		return t.AsTextRerankerRequest()
	case "jina-reranker-v2-base-multilingual":
		return t.AsTextRerankerRequest()
	case "jina-reranker-v3":
		return t.AsRerankerV3Request()
	case "jina-reranker-v3.5":
		return t.AsRerankerV3Request()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t RerankV1RerankPostJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RerankV1RerankPostJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// RerankV1RerankPost Rerank
	// (POST /v1/rerank)
	RerankV1RerankPost(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RerankV1RerankPost operation middleware
func (siw *ServerInterfaceWrapper) RerankV1RerankPost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerankV1RerankPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/rerank", wrapper.RerankV1RerankPost)

	return m
}
